#!/bin/sh
#
# Updates /etc/adblocklist to contain the latest information from
# yoyo for adblocking
#
# It expects the fileneame to put the list into as argument one
if [ $# -lt 1 ]; then
    echo "Usage: $0 output-filename"
    exit
fi

adblock_enable="$(/usr/sbin/nvram-util get adblock_enable)"

# Make sure that there is a blank file to start with
if [ -e $1 ]; then
   rm -f $1
fi
touch $1

# Only fill out the list if things enabled
if [ "x$adblock_enable" != "x1" ]; then
    exit 0;
fi

# Where the list comes from
list_src_url='http://pgl.yoyo.org/adservers/serverlist.php'
list_src_args='?hostformat=nohtml&showintro=0&mimetype=plaintext'

# the ipaddress where we want to send the requests to, instead of the
# bannerservers. We send it to a known never used address which
# iptables catches and reroutes back to us on an unusual port.

ad_catcher_ip="$(/usr/sbin/nvram-util get adblock_ip)"

if [ "x$ad_catcher_ip" = "x" ]; then ad_catcher_ip="198.51.100.1"; fi

# Where to find wget
wget=/usr/sbin/wget

# Do the work
tmpfile=/tmp/adblocklist.pre

$wget -q $list_src_url$list_src_args -O $tmpfile

while read line; do
    echo $ad_catcher_ip $line >> $1
    done < $tmpfile

rm $tmpfile
