#!/bin/sh
if [ -e /usr/etc/log_rc_flag ]; then
    echo $0 $@ >> /var/log/rc_calls
fi

adblock_hosts_file=/var/tmp/hosts.adblock
args_for_dnsmasq=""

get_dnsmasq_args() {

    dns_user_set="$(nvram-util get wan_fix_dns)"
    if [ "x$dns_user_set" == "x1" ]; then
        dns1="$(/usr/sbin/nvram-util get wan_dns1)"
        dns2="$(/usr/sbin/nvram-util get wan_dns2)"

        if [ "x$dns1" != "x" -o "x$dns2" != "x" ]; then
            args_for_dnsmasq="$args_for_dnsmasq --no-resolv"
            if [ "x$dns1" != "x" ]; then
                args_for_dnsmasq="$args_for_dnsmasq --server=$dns1"
            fi
            if [ "x$dns2" != "x" ]; then
                args_for_dnsmasq="$args_for_dnsmasq --server=$dns2"
            fi
        fi
    fi

    args_for_dnsmasq="$args_for_dnsmasq --clear_on_reload -A $adblock_hosts_file"

    dhcp_on="$(/usr/sbin/nvram-util get dhcp_server_enable)"
    if [ "x$dhcp_on" == "x1" ]; then
        dhcp_start="$(/usr/sbin/nvram-util get dhcp_start_ip)"
        dhcp_end="$(/usr/sbin/nvram-util get dhcp_end_ip)"
        mask="$(/usr/sbin/nvram-util get lan_netmask)"
        lease_length="24h"

        if [ "x$dhcp_start" != "x" && "x$dhcp_end" != "x" ]; then
            args_for_dnsmasq="$args_for_dnsmasq --dhcp-range=$dhcp_start,$dhcp_end,$mask,$lease_length --leasefile-ro --dhcp-script=/usr/sbin/dhcp_lease_update.sh"
        fi
    fi
}

case "$1" in
    start)
        get_dnsmasq_args
        /usr/sbin/get_adblock_list $adblock_hosts_file
        PID="$(pidof dnsmasq)"
        if [ "x$PID" == "x" ]; then
            /usr/sbin/dnsmasq $args_for_dnsmasq
            PID="$(pidof dnsmasq)"
            if [ "x${PID}" != "x" ]; then
	        echo "dnsmasq started succesfully. ( $args_for dnsmasq )"
	    else
	        echo "Error starting dnsmasq. ( $args_for_dnsmasq )"
	    fi
        else
            echo "dnsmasq already started, leaving it alone"
        fi
        ;;
    strop)
        echo "I'm far too polite."
        ;;
    stop)
        PID="$(pidof dnsmasq)"
	if [ "x$PID" != "x" ];then
	    /bin/kill -9 ${PID} 2>/dev/null
            echo "dnsmasq stopped."
	else
	    echo "dnsmasq is already stopped."
	fi
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1
        ;;
esac
exit 0
