#!/bin/sh
if [ -e /usr/etc/log_rc_flag ]; then
    echo "`date` [rc_firewall_wrap] $0 $@" >> /var/log/rc_calls
fi

run_netgear_rc_firewall() {
    myexec=/var/tmp/MYEXEC$$
    mybase=rc_firewall

    mkdir $myexec
    ln -fs /usr/sbin/rc_app/rc_apps $myexec/$mybase
    $myexec/$mybase $@
    rm -rf $myexec
}

case "$1" in
  init)
    /usr/sbin/rc_app/rc_adblock start
    run_netgear_rc_firewall $@
    ;;
  wan)
    if [ "x$3" = "xup" ]; then
        /usr/sbin/rc_app/rc_user_nat restart
    fi
    if [ "x$3" = "xdown" ]; then
        /usr/sbin/rc_app/rc_user_nat stop
    fi
    run_netgear_rc_firewall $@
    ;;
  inbound)
    /usr/sbin/rc_app/rc_user_nat restart
    run_netgear_rc_firewall $@
    ;;
  *)
    run_netgear_rc_firewall $@
    ;;
esac


exit 0
