#!/bin/sh
PATH=/usr/sbin

if [ -e /usr/etc/log_rc_flag ]; then
    echo "`/usr/sbin/date` [rc_lan_wrap] $0 $@" >> /var/log/rc_calls
fi

run_netgear_rc_lan() {
    myexec=/var/tmp/MYEXEC$$
    mybase=rc_lan

    mkdir $myexec
    ln -fs /usr/sbin/rc_app/rc_apps $myexec/$mybase
    $myexec/$mybase $@
    rm -rf $myexec
}

case "$1" in
  start)
    run_netgear_rc_lan $@
    /usr/sbin/rc_app/rc_passwords init
    /usr/sbin/rc_app/rc_dropbear start
    ;;
  stop)
    run_netgear_rc_lan $@
    /usr/sbin/rc_app/rc_dropbear stop
    ;;
  *)
    run_netgear_rc_lan $@
    ;;
esac


exit 0
