#!/bin/sh

tmp_file="/var/tmp/p.tmp"
ht_file="/etc/htpasswd"

rc_log() {
    if [ -e /usr/etc/log_rc_flag ]; then
        echo "`/usr/sbin/date` [rc_dropbear] $@" >> /var/log/rc_calls
    fi
}

rc_log_echo() {
    rc_log "$@"
    echo "$@"
}

rc_log "$0 $@"

case "$1" in
    init|update)
        /usr/sbin/cat $ht_file | /usr/sbin/chpasswd
        /usr/sbin/rm $tmp_file
    strop)
        echo "I'm far too polite."
        ;;
    *)
        echo "Usage: $0 init|update"
        exit 1
        ;;
esac
exit 0
