#!/bin/sh
if [ -e /usr/etc/log_rc_flag ]; then
    echo "`date` [rc_inadyn-mt] $0 $@" >> /var/log/rc_calls
fi

case "$1" in
    start)
        /usr/sbin/manage_user_nat set
        ;;
    strop)
        echo "I'm far too polite."
        ;;
    stop)
        /usr/sbin/manage_user_nat clear
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1
        ;;
esac
exit 0
