#!/bin/sh
PATH=/usr/sbin

if [ -e /usr/etc/log_rc_flag ]; then
    echo "`/usr/sbin/date` [rc_wol] $0 $@">> /var/log/rc_calls
fi

myip="$(/usr/sbin/nvram-util get lan_ipaddr)"
pnpport=56688
our_identifier="UserWOL"
upnp_cmd="/usr/sbin/upnpc -u http://$myip:$pnpport/rootDesc.xml"

wol_enable="$(/usr/sbin/nvram-util get wol_enable)"
wol_lan_ip="$(/usr/sbin/nvram-util get wol_ip)"
wol_lan_port="9"
wol_lan_mac="ff:ff:ff:ff:ff:ff"
wol_wan_port="9"

lan_interface="$(/usr/sbin/nvram-util get lan_if)"

issue_arp_on_cmd() {
    /usr/sbin/arp -i $lan_interface -s $wol_lan_ip $wol_lan_mac
}

issue_arp_off_cmd() {
    /usr/sbin/arp -i $lan_interface -d $wol_lan_ip
}

case "$1" in
    start)
        if [ "x$wol_enable" = "x1" ]; then
            issue_arp_on_cmd
            $upnp_cmd -e $our_identifier -a $wol_lan_ip $wol_lan_port $wol_wan_port udp
        fi
        ;;
    strop)
        echo "I'm far too polite."
        ;;
    stop)
        issue_arp_off_cmd
        $upnp_cmd -d $wol_wan_port udp
        ;;
    reload|restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1
        ;;
esac

