#!/bin/sh

# -----------------------------------
# $0: this script path
# $1: wan id
#

wanID=$1
userKill=$2

echo "issue $0 $wanID $userKill" >> /dev/console
echo ""  >> /dev/console

if [ "$userKill" != "1" ]; then
	/usr/sbin/rc wan auto "$wanID" "$userKill"
else
	echo "wan $wanID stopped by kill, not do auto start" > /dev/console
fi

